services:
  jellyfin:
    image: jellyfin/jellyfin
    mem_limit: 4g
    memswap_limit: 4g
    pids_limit: 512
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - ~/qbittorrent-vpn/downloads:/downloads
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
