services:
  adguardhome:
    image: adguard/adguardhome:latest
    mem_limit: 1g
    memswap_limit: 1g
    pids_limit: 256
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"       # web UI HTTP
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    labels:
      - com.centurylinklabs.watchtower.enable=true
